dist: xenial
language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR

matrix:
  include:
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=py36
      script: tox -vv
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
      # before_install:
      #   - sudo apt update
      #   - sudo apt install -y xcb xvfb libxcb-xinerama0
    - python: '3.9'
      env: TOXENV=py39
  # Added power support architecture
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=docs
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=flake8
    - arch: ppc64le
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=py36
    - arch: ppc64le
      python: '3.7'
      env: TOXENV=py37
    - arch: ppc64le
      python: '3.8'
      env: TOXENV=py38
    - arch: ppc64le
      python: '3.9'
      env: TOXENV=py39

cache:
  directories:
    - $HOME/.wheels

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - mkdir -p $PIP_WHEEL_DIR
  - pip wheel -r tests/requirements.txt
  - pip install coveralls flake8 tox wheel
  - pip install -e .

script:
  - tox

before_script: flake8 --ignore=W391 stl tests

after_success:
  - pip install codecov coveralls
  - coveralls
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  distributions: bdist_wheel
  provider: pypi
  user: WoLpH
  password:
    secure: HVxDUJ6ns7G7xypuibu01ruDfO4orV5lNr1Mor003MX3HVivvKsTwWqY5K1J+J+C4mgK6ahyvanD5GahYvcWia/Y2xeH2VnytnAgo+W3AI+h72+1oaRpvQHynJ7Fz6Mc0zad0GcbQh3QuA7Pu3IOWs7buUL+MQM6d9QLTkerOvs=
  on:
    tags: true
    repo: WoLpH/numpy-stl
